### ISSUE TITLE
First line of multiline stack traces truncated

### ISSUE THREAD

**Issue by heytrav** [saymedia/journald-cloudwatch-logs#21]
I've gotten this going on our servers and sending journal logs to CloudWatch. I believe I've set everything up identically to the README.

I've noticed a strange behaviour when comparing the logs I see in CloudWatch with those on the box. My application outputs multiline stack traces like the following:

```
{ 500 Internal errror
    at /path/to/something.js line 382
    .
    .
    .
```
Running `journalctl -f -u <myservice>` I see lines like:

```
July 23 17:05:25 ip-22-34-55-66 my-app[234]: { 500 Internal error
July 23 17:05:25 ip-22-34-55-66 my-app[234]:     at /path/to/something.js line 382
```

But, in CloudWatch, I never see the first line (the one with `{ 500 Internal error`) which is a bit bothersome because this is what I need to filter on.

Any advice what I might be missing?

**Comment by apparentlymart** [comment]
Sorry this isn't working as expected, @heytrav.

:thinking: I'm not really sure what's going on here but my first guess would be that the initial `{` (assuming that was a literal representation of what you're writing) is causing this to be treated as a JSON log line, but it's then being ignored because it's not valid JSON.

**Comment by heytrav** [comment]
I'm seeing the same behaviour with lines that do not have a `{` in them:

In journalctl I see the following:
```
July 23 17:05:25 ip-22-34-55-66 my-app[234]: Unhandled error for request POST /user-registration-api/User/registrations: ForbiddenError: invalid csrf token
July 23 17:05:25 ip-22-34-55-66 my-app[234]:     at csrf (/srv/bro-api/node_modules/csurf/index.js:112:19)

```

But in CloudWatch, the first line with `Unhandled error for request` does not appear at all, while the following line: `     at csrf (/srv/bro-` does appear. I've tried just searching with `{$.message = "Unhandled*"}` but no luck.

**Comment by apparentlymart** [comment]
Hmm... that's very interesting. I've not seen things behave in this way... do you know if the app is delivering this data to journald as a single message, or if it's being sent as separated lines e.g. via `syslogd`?

**Comment by heytrav** [comment]
If I understand correctly the app is logging to stdout/stderr. I don't really have a lot of experience with journald or systemd in general, but here is the systemd config. How would you configure something to log ot journald directly?

```
[Service]
ExecStart=/usr/bin/node /srv/my-app/server/server.js
Restart=always
SyslogIdentifier=my-app
User=srv-loopback
Group=srv-loopback
Environment=NODE_ENV=production
[Install]
WantedBy=multi-user.target
```

**Comment by apparentlymart** [comment]
Ahh, interesting... so I guess in this case systemd (in its role as the supervisor of the app) must be doing line-buffering of stderr/stdout and writing the resulting lines to journald separately. Otherwise I'm not sure how it would know what are the boundaries of a message, since stdout/stderr are just byte streams.

I'm honestly not too familiar with the details here myself, but the fact that this is being driving by the stdio streams makes me even more confused as to how the first line would be treated differently here, since by the time the data is written to stderr the notion of a "log message" has been lost and it's all just a flat sequence of bytes.

As it currently stands `journald-cloudwatch-logs` doesn't have a great deal of logging of its own, since we were concerned about it creating feedback loops where it would end up consuming its own errors and producing more errors. If you're willing to get your hands dirty with some Go programming, you could perhaps try turning up the log level on the AWS client (some examples of this in aws/aws-sdk-go#315) to get it to print out the request it's making, and then see if the first line is being excluded when requests are sent to the cloudwatch logs API, or if that's getting lost in the remote logic somewhere.

I'm sorry I don't have anything more concrete/helpful to offer here. :confounded:

**Comment by heytrav** [comment]
Ok, well I might check and see if the node.js logging library that we're using has some facility for logging directly to journald.

I do have another question relating to the way the application starts. Since I'm a complete novice w.r.t. systemd I just put your example service file in as it was in the README. However I've noticed on restarting my machine that journald-cloudwatch-logs doesn't start at boot up. I'm wondering if it has something to do with the `Units` you've specified (i.e. I don't know if those were just there as examples or if they actually are needed).

**Comment by apparentlymart** [comment]
IIRC it's the `Wants` setting that makes it come up at boot. "basic.target" represents booting the system. (I'm a little rusty on this myself; [the systemd docs on `Unit`](https://www.freedesktop.org/software/systemd/man/systemd.unit.html) explain these settings, though.)

**Comment by heytrav** [comment]
So we have fixed this by logging out as JSON
