### ISSUE TITLE
Not using an existing logstream when run from a new instance

### ISSUE THREAD

**Issue by heytrav** [saymedia/journald-cloudwatch-logs#22]
Our team currently uses logstreams based on the host name (eg. backend.test01.services.com). We rebuild our hosts pretty regularly (nightly in some cases).

When I rebuild my machine so that I am effectively running a completely new instance, the logstream I was using on the original instance does not receive any new logs even though the logstream exists and has the same name (the last entry is always the final entry in the original instance). 

I've only been able to again start collecting logs by deleting the existing logstream in CloudWatch. Once I do that then I presume journald-cloudwatch-logs recreates the logstream again and logs start appearing in CloudWatch again.

Should the journald-cloudwatch-logs actually be able to reuse an existing log stream or do I have to use some other naming scheme?

**Comment by apparentlymart** [comment]
Hi @heytrav!

The Cloudwatch Logs API has this idea of a _sequence token_ which is returned on each write and must be provided on the next read. `journald-cloudwatch-logs` keeps track of the last sequence token it saw in its state file when it is cleanly shut down, so it can resume where it left off on the next run.

I expect what's happening here is that when you spin the fresh instance the state is getting reset (since it existed only in the old instance disk) and so `journald-cloudwatch-logs` is getting errors when it tries to write to the stream _without_ a sequence token.

As currently implemented, the assumption was that the log stream name would change each time a fresh instance is spun up. In the saymedia environment, for example, the log stream name is the EC2 instance id, and so it is never reused on a new system.

IIRC there is a separate API operation on cloudwatch logs that allows retrieving the most recent sequence token. One thing you could do here is use a helper program on boot that reproduces the `journald-cloudwatch-logs` state file after calling that API endpoint. In principle this program could try to do this itself; it doesn't today as a means to prevent two concurrent writers to the same stream, which is assumed to be an error, but perhaps there could be a CLI option `-append` that opts into this automatic sequence token sync behavior to make things easier in situations like yours where instances have "pet names" that are passed on from one generation to the next.

I don't myself have time to work on such a thing right now, but I'd be happy to review a patch for it if you have the time and motivation to work on it.

**Comment by heytrav** [comment]
Thanks @apparentlymart 

I probably won't be able to do much in that regard; at least not right away.

I might have to just append the instance id and date to the host name to make sure they're unique. I'm a little ambivalent about it because it means we'll end up with lots of log streams as instances get instances get rebuilt every night, but it should work as an interrim solution.

**Comment by heytrav** [comment]
>I might have to just append the instance id and date to the host name to make sure they're unique

This solution seems to be working ok.
