### ISSUE TITLE
Compile Error sdjournal/journal.go:27:33

### ISSUE THREAD

**Issue by owaincuvelier** [saymedia/journald-cloudwatch-logs#23]
hey, bit of a `Go` novice here, trying to get this program up and running. 

When I run `go get github.com/saymedia/journald-cloudwatch-logs/` 

It returns: 

```
# github.com/saymedia/journald-cloudwatch-logs/vendor/github.com/coreos/go-systemd/sdjournal
.gvm/pkgsets/go1.7.6/global/src/github.com/saymedia/journald-cloudwatch-logs/vendor/github.com/coreos/go-systemd/sdjournal/journal.go:27:33: fatal error: systemd/sd-journal.h: No such file or directory
 // #include <systemd/sd-journal.h>
                                 ^
compilation terminated.
```

I'm not sure if I'm misunderstanding something or if this is an issue. It seems to be failing on a 
commented out piece of code. The error I think is coming from the use of a # after the comment slashes. If I'm doing anything obtusely incorrect please let me know!

**Comment by owaincuvelier** [comment]
As an aside, I've been using GVM to try different versions of Go to see if I could get this running.

**Comment by owaincuvelier** [comment]
I think this may have been related: https://github.com/coreos/go-systemd/issues/201

**Comment by apparentlymart** [comment]
Hi @owaincuvelier!

As I think you've now figured out (but restating for anyone else who finds this in future), `journald-cloudwatch-logs` talks to journald via the systemd C library, so building this application requires that library's headers and libs to be installed on the system.

The `// #include` syntax here is a hint to Go's C interface (CGo) that it should look in that header file to find the definitions for this API.

On a Debian- or Ubuntu-based system, `apt-get install libsystemd-dev` should do the trick to make it build.  _Running_ the compiled application will require `libsystemd0`, but I think that's part of the Debian and Ubuntu base systems so probably doesn't require any additional action. (Not actually tested, since I don't currently have a fresh Debian or Ubuntu system handy to try.)
